### ISSUE TITLE
Deployment Status and Container Health Issue

### ISSUE THREAD

**Issue by abbdulwahab86** [5GSEC/5G-Spector#11]
Hi there, Can you guide me why status and ready columns are not showing as desired.
<pre><font color="#4E9A06"><b>gspector@gspector-virtual-machine</b></font>:<font color="#3465A4"><b>~/Desktop/ric-dep/bin</b></font>$ sudo helm list -A
NAME             	NAMESPACE	REVISION	UPDATED                                	STATUS  	CHART               	APP VERSION
r4-a1mediator    	ricplt   	1       	2024-12-03 13:47:39.150458017 +0500 PKT	deployed	a1mediator-3.0.0    	1.0        
r4-alarmmanager  	ricplt   	1       	2024-12-03 13:48:12.589011128 +0500 PKT	deployed	alarmmanager-5.0.0  	1.0        
r4-appmgr        	ricplt   	1       	2024-12-03 13:47:05.294756428 +0500 PKT	deployed	appmgr-3.0.0        	1.0        
r4-dbaas         	ricplt   	1       	2024-12-03 13:46:56.950162386 +0500 PKT	deployed	dbaas-2.0.0         	1.0        
r4-e2mgr         	ricplt   	1       	2024-12-03 13:47:22.168389702 +0500 PKT	deployed	e2mgr-3.0.0         	1.0        
r4-e2term        	ricplt   	1       	2024-12-03 13:47:30.62476667 +0500 PKT 	deployed	e2term-3.0.0        	1.0        
r4-infrastructure	ricplt   	1       	2024-12-03 13:46:46.384217504 +0500 PKT	deployed	infrastructure-3.0.0	1.0        
r4-o1mediator    	ricplt   	1       	2024-12-03 13:48:04.160033941 +0500 PKT	deployed	o1mediator-3.0.0    	1.0        
r4-rtmgr         	ricplt   	1       	2024-12-03 13:47:13.818539591 +0500 PKT	deployed	rtmgr-3.0.0         	1.0        
r4-submgr        	ricplt   	1       	2024-12-03 13:47:47.510255184 +0500 PKT	deployed	submgr-3.0.0        	1.0        
r4-vespamgr      	ricplt   	1       	2024-12-03 13:47:55.853959645 +0500 PKT	deployed	vespamgr-3.0.0      	1.0        
<font color="#4E9A06"><b>gspector@gspector-virtual-machine</b></font>:<font color="#3465A4"><b>~/Desktop/ric-dep/bin</b></font>$ sudo kubectl get pods -n ricplt
NAME                                                         READY   STATUS                  RESTARTS   AGE
deployment-ricplt-a1mediator-64fd4bf64-lfcmd                 0/1     ImagePullBackOff        0          27m
deployment-ricplt-alarmmanager-7d47d8f4d4-7dwlp              0/1     ImagePullBackOff        0          26m
deployment-ricplt-appmgr-79848f94c-jvjlw                     0/1     Init:ImagePullBackOff   0          28m
deployment-ricplt-e2mgr-856f655b4-zqcx5                      0/1     ImagePullBackOff        0          27m
deployment-ricplt-e2term-alpha-d5fd5d9c6-j249f               0/1     ImagePullBackOff        0          27m
deployment-ricplt-o1mediator-76c4646878-cdrp9                0/1     ImagePullBackOff        0          27m
deployment-ricplt-rtmgr-6556c5bc7b-kfhnb                     0/1     ImagePullBackOff        0          27m
deployment-ricplt-submgr-66485ccc6c-bzsmw                    0/1     ErrImagePull            0          27m
deployment-ricplt-vespamgr-786666549b-kzssd                  0/1     ImagePullBackOff        0          27m
r4-infrastructure-kong-5986fc7965-5wnmb                      0/2     Init:ImagePullBackOff   0          28m
r4-infrastructure-prometheus-alertmanager-64f9876d6d-9ksp9   0/2     ErrImagePull            0          28m
r4-infrastructure-prometheus-server-bcc8cc897-fxhn8          0/1     ImagePullBackOff        0          28m
statefulset-ricplt-dbaas-server-0                            0/1     ImagePullBackOff        0          28m
<font color="#4E9A06"><b>gspector@gspector-virtual-machine</b></font>:<font color="#3465A4"><b>~/Desktop/ric-dep/bin</b></font>$ sudo kubectl get pods -n ricinfra
NAME                                         READY   STATUS              RESTARTS   AGE
deployment-tiller-ricxapp-676dfd8664-hwh22   0/1     ContainerCreating   0          28m
tiller-secret-generator-gghd6                0/1     ImagePullBackOff    0          28m
</pre>
<pre><font color="#4E9A06"><b>gspector@gspector-virtual-machine</b></font>:<font color="#3465A4"><b>~/Desktop/ric-dep/bin</b></font>$ curl -v http://192.168.44.129:32080/appmgr/ric/v1/health/ready
*   Trying 192.168.44.129:32080...
* TCP_NODELAY set
* connect to 192.168.44.129 port 32080 failed: Connection refused
* Failed to connect to 192.168.44.129 port 32080: Connection refused
* Closing connection 0
curl: (7) Failed to connect to 192.168.44.129 port 32080: Connection refused
<font color="#4E9A06"><b>gspector@gspector-virtual-machine</b></font>:<font color="#3465A4"><b>~/Desktop/ric-dep/bin</b></font>$ curl -v http://localhost:32080/appmgr/ric/v1/health/ready
*   Trying 127.0.0.1:32080...
* TCP_NODELAY set
* connect to 127.0.0.1 port 32080 failed: Connection refused
* Failed to connect to localhost port 32080: Connection refused
* Closing connection 0
curl: (7) Failed to connect to localhost port 32080: Connection refused
</pre>

**Comment by onehouwong** [comment]
Your k8s cluster failed to pull the O-RAN SC docker images. Could you share the output of `kubectl describe pod deployment-ricplt-a1mediator-64fd4bf64-lfcmd  -n ricplt`? For O-RAN SC deployment issues, you may want to check their issue page at https://lf-o-ran-sc.atlassian.net/jira/projects?page=1&sortKey=name&sortOrder=ASC

**Comment by abbdulwahab86** [comment]
Thanks. issue resolved.
