### ISSUE TITLE
Error while deploying the core network

### ISSUE THREAD

**Issue by m-wojnar** [5GSEC/5G-Spector#3]
Dear 5G-Spector developers,

I have a problem while deploying the core network. I followed the installation instructions on the "5G‐Spector Artifact in a Simulated LTE Network" wiki page and was able to successfully download the VM, install the dependencies, and import and run the VM. However, when I run the `make omen` command, I get an error:

```
error: timed out waiting for the condition on pods/upf-0
mk/epc.mk:11: recipe for target '/home/vagrant/sdran-in-a-box//workspace/milestones/omec' failed
make: *** [/home/vagrant/sdran-in-a-box//workspace/milestones/omec] Error 1
```

Running the command `kubectl get pods -n riab` gives the result:
```
NAME          READY   STATUS             RESTARTS       AGE
cassandra-0   1/1     Running            0              7m37s
hss-0         1/1     Running            0              7m37s
mme-0         4/4     Running            0              7m37s
pcrf-0        1/1     Running            0              7m37s
spgwc-0       2/2     Running            0              7m37s
upf-0         2/4     CrashLoopBackOff   11 (34s ago)   6m21s
```

I tried following the troubleshooting section and restarting all services, but failed to resolve the problem with commands:
```
cd ~/sdran-in-a-box
make reset-test && make omec && make OPT=ric
```

I am using a fresh installation of Ubuntu 24.04 on an x86-64 machine.

**Comment by onehouwong** [comment]
Could you provide the log of the `upf-0` container that has crashed?

For example: `kubectl logs upf-0 -n riab --previous`

**Comment by m-wojnar** [comment]
Of course, the command `kubectl logs upf-0 -n riab --previous` gives me an output:
```
error: a container name must be specified for pod upf-0, choose one of: [bessd routectl web cpiface] or one of the init containers: [bess-init]
```

Below are the outputs for the following containers:
- `bessd`
```
+ bessd -m 0 -f -grpc-url=0.0.0.0:10514
```

- `routectl`
```
/opt/bess/bessctl/conf/route_control.py:311: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if item.prefix_len is 0:
Deprecation warning https://docs.pyroute2.org/ipdb_toc.html
Connecting to BESS daemon...
Error connecting to BESS daemon. Retrying in 2sec...
Error connecting to BESS daemon. Retrying in 2sec...
Error connecting to BESS daemon. Retrying in 2sec...
Error connecting to BESS daemon. Retrying in 2sec...
Error connecting to BESS daemon. Retrying in 2sec...
Traceback (most recent call last):
  File "/opt/bess/bessctl/conf/route_control.py", line 517, in <module>
    main()
  File "/opt/bess/bessctl/conf/route_control.py", line 483, in main
    connect_bessd()
  File "/opt/bess/bessctl/conf/route_control.py", line 438, in connect_bessd
    raise Exception('BESS connection failure.')
Exception: BESS connection failure.
```

- `web`
```
Error from server (BadRequest): previous terminated container "web" in pod "upf-0" not found
```

- `cpiface`
```
Error from server (BadRequest): previous terminated container "cpiface" in pod "upf-0" not found
```

- `bess-init`
```
Error from server (BadRequest): previous terminated container "bess-init" in pod "upf-0" not found
```

**Comment by onehouwong** [comment]
Thanks for sharing the logs. It looks like the connection to the BESS daemon has failed. So far we haven't run into this issue and we could not offer a solution for this. We notice you have been running with ubuntu 24.04 as the host, which might be the problem. The SD-RAN RiAB environment has been tested on ubuntu 18.04 (https://docs.sd-ran.org/master/sdran-in-a-box/docs/HW_Installation_intro.html) so it might be better to use the same version.

**Comment by m-wojnar** [comment]
Thank you for your feedback. I'll consider downgrading to Ubuntu 18.04 as suggested and retesting the environment.

**Comment by HUAYAN999** [comment]
I'm also trying to simulate a 5G-Spector artifact in an LTE network, but I can't get the VM image, it shows that the link is expired, how do I get the image?

**Comment by yanggao017** [comment]
> I'm also trying to simulate a 5G-Spector artifact in an LTE network, but I can't get the VM image, it shows that the link is expired, how do I get the image?
 You can download it from https://zenodo.org/records/10154551
