### ISSUE TITLE
public key issue | Kubectl not available

### ISSUE THREAD

**Issue by bergen876** [5GSEC/5G-Spector#5]
Hi 5G-Spector Team, 

thank you for this work. it has been immensely helpful.  I am seeking your help with the following issue. 

the artifact was working perfectly without issues, then I started to recieve this error about kubernetes. 

vagrant@5g-spector:~$ kubectl get pods -A
The connection to the server 127.0.0.1:6443 was refused - did you specify the right host or port?
vagrant@5g-spector:~$

After checking a few items i notice that kubernetes service was no longer found on the vm. 

So i performed a vagrant destroy and started to rebuild the vm from scratch. 

But i started to encounter this issue with public key when it runs the inline scrip in the Vagrant file ( presumably the apt-get update) 

==> 5g-spector: Mounting NFS shared folders...
==> 5g-spector: Configuring and enabling network interfaces...
==> 5g-spector: Running provisioner: shell...
    5g-spector: Running: inline script
    5g-spector:
    5g-spector: WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
    5g-spector:
    5g-spector: Get:1 https://apt.kitware.com/ubuntu bionic InRelease [15.6 kB]
    5g-spector: Hit:2 http://us.archive.ubuntu.com/ubuntu bionic InRelease
    5g-spector: Hit:3 http://us.archive.ubuntu.com/ubuntu bionic-updates InRelease
    5g-spector: Hit:4 http://us.archive.ubuntu.com/ubuntu bionic-backports InRelease
    5g-spector: Err:1 https://apt.kitware.com/ubuntu bionic InRelease
    5g-spector:   The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 1A127079A92F09ED
    5g-spector: Get:5 https://download.docker.com/linux/ubuntu bionic InRelease [64.4 kB]
    5g-spector: Hit:6 http://security.ubuntu.com/ubuntu bionic-security InRelease
    5g-spector: Fetched 80.0 kB in 1s (65.8 kB/s)
    5g-spector: Reading package lists...
    5g-spector: Building dependency tree...
    5g-spector: Reading state information...
    5g-spector: 93 packages can be upgraded. Run 'apt list --upgradable' to see them.
    5g-spector: W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://apt.kitware.com/ubuntu bionic InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 1A127079A92F09ED
    5g-spector: W: Failed to fetch https://apt.kitware.com/ubuntu/dists/bionic/InRelease  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 1A127079A92F09ED
    5g-spector: W: Some index files failed to download. They have been ignored, or old ones used instead.
    5g-spector:
    5g-spector: WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
    5g-spector:
    5g-spector: Reading package lists...
    5g-spector: Building dependency tree...
    5g-spector: Reading state information...
    5g-spector: ethtool is already the newest version (1:4.15-0ubuntu1).
    5g-spector: httpie is already the newest version (0.9.8-2).
    5g-spector: jq is already the newest version (1.5+dfsg-2).
    5g-spector: ipvsadm is already the newest version (1:1.28-3ubuntu0.18.04.1).
    5g-spector: software-properties-common is already the newest version (0.96.24.32.22).
    5g-spector: python3-pip is already the newest version (9.0.1-2.3~ubuntu1.18.04.8).
    5g-spector: The following packages were automatically installed and are no longer required:
    5g-spector:   libpython-stdlib libpython2.7-minimal libpython2.7-stdlib openvswitch-common
    5g-spector:   python python-minimal python-six python2.7 python2.7-minimal
    5g-spector: Use 'sudo apt autoremove' to remove them.
    5g-spector: 0 upgraded, 0 newly installed, 0 to remove and 93 not upgraded.

i would really appreciate any insights that you may have into this issue . 

Thank you !

**Comment by onehouwong** [comment]
Rebuilding the vm from scratch might not be a good idea. Could you redownload the artifact, in particular the `.box` file and import it with vagrant?

**Comment by bergen876** [comment]
Thanks for responding,  I re-downloaded the artifact and attempted the import. However, the issue still persists. 

I have even tried from a fresh server and the same error happens.

Are you able to replicate the error ?

![image](https://github.com/user-attachments/assets/e1589344-2188-481f-a86a-19bda704436e)


![image](https://github.com/user-attachments/assets/22d0f7a7-5a2f-43c3-93cc-96302b9c69c5)

**Comment by onehouwong** [comment]
It appears the vm has started successfully. The error from the `kubectl` command has nothing to do with the apt update error I believe. Usually you just need to wait for a few minutes until the k8s service is started.

**Comment by bergen876** [comment]
it seems that the apt update wasnt able to be performed thus causing the k8s to not be configured. I am unable to find K8s on the VM.  Can i go ahead and set it up ? 

![image](https://github.com/user-attachments/assets/8d610c1a-1d14-430c-bbb4-a4de5534b9ec)

**Comment by onehouwong** [comment]
Maybe try importing the GPG key and see if you can run apt in the vm?

**Comment by bergen876** [comment]
I’ve found a solution for the update failure, which involves adding Kitware's GPG key to the trusted keyring.

wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | sudo tee /usr/share/keyrings/kitware-archive-keyring.gpg >/dev/null
