### ISSUE TITLE
K8s Certificate expired || error: You must be logged in to the server (Unauthorized) 

### ISSUE THREAD

**Issue by bergen876** [5GSEC/5G-Spector#7]
I've discovered that the k8s certs have expired which has resulted in Kubectl failing with the titled error 

![image](https://github.com/user-attachments/assets/ccd61f84-dccc-4717-8758-0fe2379995ba)

Could you consider updating the VMs box image with the updated certificate? 

However, I have included the following steps that I used to work around the issue. 

**************************** Work Around *******************************************

Firstly reset rke2 by running 

_sudo rke2 server --cluster-reset_

Remove old data from the etcd data directory if you get a error when running the cluster reset  
_sudo rm -rf /var/lib/rancher/rke2/server/db/etcd_
![image](https://github.com/user-attachments/assets/b88a2133-c79e-4b14-8681-1be636615f8a)

The deployment uses rke2 as the Kubernetes manager. You will need to rotate the certificates there 
 _sudo rke2 certificate rotate_

![image](https://github.com/user-attachments/assets/f2c71aa9-2b5c-4aff-a3a2-755bdb317024)

then restart rk2 by running 

__sudo systemctl restart rke2-server__

Confirm that its started by  _sudo systemctl restart rke2-server_

![image](https://github.com/user-attachments/assets/df4336ba-288a-4495-8a22-63b6d84d5860)

test that kubectl is  working by running 

_sudo kubectl --kubeconfig /etc/rancher/rke2/rke2.yaml get pods --all-namespaces_

Now to replace the Kubernetes configurations with the updated certificate information by modifying the Kube config file  by updating it with the updated  rke config

_REPLACE  vagrant@5g-spector:~/.kube$  config  WITH  /etc/rancher/rke2/rke2.yaml}_

Test by running 
_kubectl get pods -A_

**Comment by onehouwong** [comment]
There seems to be another fix for this error: https://serverfault.com/questions/1032367/kubectl-get-nodes-error-you-must-be-logged-in-to-the-server-unauthorized-ho
